# Common Configurations
spring.application.name=commerce-service
spring.profiles.active=local

# JPA/Hibernate Common
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Datasource - Se debe configurar en docker-compose o env vars
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:smartstock}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:smartstock}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Logging Configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/commerce-service.log

server.port=8085

smartstock.jwt.secret=${SMARTSTOCK_JWT_SECRET:smartstock_super_secret_key_2026_jwt_token_must_be_long_enough}
smartstock.jwt.expiration=86400000
