server.port=8080
spring.application.name=smartstock-bff-service

# URLs de los microservicios (en docker-compose se usarán los nombres de servicio)
smartstock.auth-service.url=http://localhost:8081
smartstock.inventory-service.url=http://localhost:8082
smartstock.finance-service.url=http://localhost:8083
smartstock.alert-service.url=http://localhost:8084

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Logging
logging.level.com.osanzana.smartstock.bff=DEBUG
